<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>GOHT-Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="XResources\CrossResources.cs~RFda0d914.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="GOHT-Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AssetsTools.NET">
      <HintPath>AssetsToolsLibs\AssetsTools.NET.dll</HintPath>
    </Reference>
    <Reference Include="AssetsTools.NET.MonoCecil">
      <HintPath>AssetsToolsLibs\AssetsTools.NET.MonoCecil.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>