<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>GOHT-Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="GOHT-Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AssetsTools.NET">
      <HintPath>AssetsToolsLibs\AssetsTools.NET.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>